LeftPanel = left panel
ResetApplication = reset application
ResetGui = reset GUI
CalculationPanel = calculation panel
CompositionPanel = composition panel
ConfigurationPanel = configuration panel
Language = language

Unsigned = Unsigned
    .hover = Round negative values to zero.
Precision = Precision
Round = Round
    .hover = Round
Properties = Properties
    .hover = Properties
Relative = Relative
    .hover = Use relative base
ToRelative = To relative
    .hover = Convert experimental stereospecific number 2 values to relative