Language = Language
    .hover= Select language
LeftPanel = Left panel
    .hover = Show/hide left panel
ResetApplication = Reset application
    .hover= Reset application data
ResetGui = reset GUI
    .hover= Reset application GUI

### Settings

Composition = Composition
    .hover = Triacylglycerol composition
Composition_Mass_Monospecific = Mass, mono
    .abbreviation = MMC
    .hover = Mass non-stereospecific composition
Composition_Mass_Stereospecific = Mass, stereo
    .abbreviation = MSC
    .hover = Mass stereospecific composition (agregation)
Composition_EquivalentCarbonNumber_Monospecific = ECN, mono
    .abbreviation = NMC
    .hover = Equivalent carbon number non-stereospecific composition (agregation)
Composition_EquivalentCarbonNumber_Stereospecific = ECN, stereo
    .abbreviation = NSC
    .hover = Equivalent carbon number stereospecific composition
Composition_Species_Monospecific = Species, mono
    .abbreviation = SMC
    .hover = Species non-stereospecific composition (permutation)
Composition_Species_Positionalspecific = Species, positional
    .abbreviation = SPC
    .hover = Species positional specific composition (permutation)
Composition_Species_Stereospecific = Species, stereo
    .abbreviation = SSC
    .hover = Species stereospecific composition
Composition_Type_Monospecific = Type, mono
    .abbreviation = TMC
    .hover = Type non-stereospecific composition (permutation)
Composition_Type_Positionalspecific = Type, positional
    .abbreviation = TPC
    .hover = Type positional specific composition (permutation)
Composition_Type_Stereospecific = Type, stereo
    .abbreviation = TSC
    .hover = Type stereospecific composition
Composition_Unsaturation_Monospecific = Unsaturation, mono
    .abbreviation = UMC
    .hover = Unsaturation non-stereospecific composition (agregation)
Composition_Unsaturation_Stereospecific = Unsaturation, stereo
    .abbreviation = USC
    .hover = Unsaturation stereospecific composition
Filter = Filter
    .hover = Filter rows by set operation
Filter_Intersection = Intersection
    .hover = Non-zero values are present in all columns (AND)
Filter_Union = Union
    .hover = Non-zero values are present in one or more columns (OR)
Filter_Difference = Difference
    .hover = Non-zero values are missing in one or more columns (XOR)
Percent = Percent
    .hover = Display of values in percent
Precision = Precision
    .hover = Number of decimal pieces
Threshold = Threshold
    .hover = Value in one or more columns greater than threshold
Truncate = Truncate
    .hover = Truncate header text
Sort = Sort
    .hover = Sort rows by
Sort_Key = Key
    .hover = Sort by key
Sort_Value = Value
    .hover = Sort by value
Metric = { $PluralCategory ->
    *[one] Metric
    [other] Metrics
}
Parameters = Parameters
